# Site
name: 'Markerbench'
description: 'This is the personal blog of Andrew Jaquith. My interests include security, anything mobile, app development, visualization, good writing and spirited discussion.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'markerbench'
email: ''
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    arj:
      name:           Andrew Jaquith
      site:           https://www.markerbench.com
      avatar:         arj.jpg
      bio:            'I&rsquo;m <a href="http://www.linkedin.com/in/ajaquith">Andrew Jaquith</a>, a Wall St Managing Director. Previously, I was CTO <a href="http://www.silversky.com">SilverSky</a>, and former analyst with <a href="http://www.forrester.com">Forrester</a> and <a href="http://www.yankeegroup.com">Yankee Group</a>. My interests include security and risk, anything data-related, app development, visualization, good writing and spirited discussion.'
      email:
      twitter:        https://twitter.com/arj

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: arj
      avatar: arj.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Google Analytics
google_analytics_tracking_id: UA-37546435-1

# Jekyll assets
assets:
  compression: true
